### ISSUE TITLE
No longer builds

### ISSUE THREAD

**Issue by jrp2014** [BartoszMilewski/XOperad#3]
Hi Bartosz,  I haven't managed to get this to compile.  Seems a bit odd, as the `(+)` type family seems OK.  Suggestions? 

```
❯ cabal build
Resolving dependencies...
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - XOperad-0.1.0.0 (lib) (first run)
 - XOperad-0.1.0.0 (exe:tic-tac-toe) (first run)
Configuring library for XOperad-0.1.0.0..
Preprocessing library for XOperad-0.1.0.0..
Building library for XOperad-0.1.0.0..
[1 of 5] Compiling Numbers          ( Numbers.hs, /Users/xxx/Documents/Haskell/XOperad/dist-newstyle/build/x86_64-osx/ghc-8.10.4/XOperad-0.1.0.0/build/Numbers.o, /Users/xxx/Documents/Haskell/XOperad/dist-newstyle/build/x86_64-osx/ghc-8.10.4/XOperad-0.1.0.0/build/Numbers.dyn_o )

Numbers.hs:26:15: error:
    Not in scope: type constructor or class ‘Z’
   |
26 | type instance Z * m = Z
   |               ^

Numbers.hs:27:16: error:
    Not in scope: type constructor or class ‘S’
   |
27 | type instance (S n) * m = m + (n * m)
   |                ^
cabal: Failed to build XOperad-0.1.0.0 (which is required by exe:tic-tac-toe
from XOperad-0.1.0.0).
```

**Comment by BartoszMilewski** [comment]
Fixed!

**Comment by jrp2014** [comment]
Many thanks, Bartosz.  I've been having a play myself.  As well as similar fixes to yours , some stylistic tweaks and updated CI / cabal / stack.

Happy to send you a pull request from https://github.com/jrp2014/XOperad

I have a Count 4 solver that I'd like to transform to using your approach.  (It currently uses rose trees (cofree comonads without knowing it!) to track the game state.  It does this in Bird style, without indexes, etc, so I may not need the type level peano number machinery.

Anyway, thanks for putting out all this invaluable material.
